/* Daftar mata uang ISO 4217 lengkap.
 *
 * Dulu berisi 12 entri buatan tangan dan hanya dipakai AddProject, sementara
 * tiga halaman lain masing-masing punya daftar hardcode sendiri berisi 3-4 mata
 * uang. Sekarang satu sumber untuk semuanya.
 *
 * Dua belas mata uang yang paling sering dipakai sengaja ditaruh di depan
 * supaya muncul lebih dulu tanpa perlu mengetik; sisanya urut abjad. Pencarian
 * di StyledSelect mencocokkan kode maupun namanya.
 *
 * Simbol dua belas entri pertama dipertahankan dari daftar lama supaya tampilan
 * yang sudah berjalan tidak berubah diam-diam — data Intl memberi '$' polos
 * untuk SGD dan AUD, yang justru rancu.
 *
 * Dibangkitkan dari Intl.supportedValuesOf('currency') pada Node 22.
 */
export const currencyList = [
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
  { code: 'USD', name: 'US Dollar', symbol: '$' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'GBP', name: 'British Pound', symbol: '£' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'SR' },
  { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'AED' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: 'AFN' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'ALL' },
  { code: 'AMD', name: 'Armenian Dram', symbol: 'AMD' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ANG' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'AOA' },
  { code: 'ARS', name: 'Argentine Peso', symbol: 'ARS' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'AWG' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: 'AZN' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'BAM' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'BBD' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: 'BDT' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'BGN' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BHD' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'BIF' },
  { code: 'BMD', name: 'Bermudan Dollar', symbol: 'BMD' },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'BND' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'BOB' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: 'BSD' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'BTN' },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'BWP' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'BYN' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZD' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'CDF' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CLP' },
  { code: 'COP', name: 'Colombian Peso', symbol: 'COP' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: 'CRC' },
  { code: 'CUC', name: 'Cuban Convertible Peso', symbol: 'CUC' },
  { code: 'CUP', name: 'Cuban Peso', symbol: 'CUP' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'CVE' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'CZK' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'DJF' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'DKK' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'DOP' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DZD' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'EGP' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'ERN' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'ETB' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJD' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: 'FKP' },
  { code: 'GEL', name: 'Georgian Lari', symbol: 'GEL' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GHS' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: 'GIP' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'GMD' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'GNF' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'GTQ' },
  { code: 'GYD', name: 'Guyanaese Dollar', symbol: 'GYD' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'HNL' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'HRK' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'HTG' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'HUF' },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'IQD' },
  { code: 'IRR', name: 'Iranian Rial', symbol: 'IRR' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'ISK' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'JMD' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JOD' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KES' },
  { code: 'KGS', name: 'Kyrgystani Som', symbol: 'KGS' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: 'KHR' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'KMF' },
  { code: 'KPW', name: 'North Korean Won', symbol: 'KPW' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KWD' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'KYD' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: 'KZT' },
  { code: 'LAK', name: 'Laotian Kip', symbol: 'LAK' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'LBP' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'LKR' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'LRD' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'LSL' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LYD' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'MDL' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'MGA' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'MKD' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'MMK' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: 'MNT' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'MRU' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: 'MUR' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'MVR' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MWK' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MZN' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'NAD' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: 'NGN' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'NIO' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'NOK' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'NPR' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'OMR' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'PAB' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'PEN' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'PGK' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: 'PKR' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'PLN' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: 'PYG' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'QAR' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'RON' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'RSD' },
  { code: 'RUB', name: 'Russian Ruble', symbol: 'RUB' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RWF' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SBD' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: 'SCR' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'SEK' },
  { code: 'SHP', name: 'St. Helena Pound', symbol: 'SHP' },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'SLE' },
  { code: 'SLL', name: 'Sierra Leonean Leone (1964—2022)', symbol: 'SLL' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'SOS' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: 'SRD' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: 'SSP' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'STN' },
  { code: 'SVC', name: 'Salvadoran Colón', symbol: 'SVC' },
  { code: 'SYP', name: 'Syrian Pound', symbol: 'SYP' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'SZL' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'TJS' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'TMT' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'TND' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'TOP' },
  { code: 'TRY', name: 'Turkish Lira', symbol: 'TRY' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: 'TTD' },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TZS' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: 'UAH' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'UGX' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: 'UYU' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'UZS' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'VES' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VUV' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WST' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$' },
  { code: 'XCG', name: 'Caribbean guilder', symbol: 'Cg.' },
  { code: 'XDR', name: 'Special Drawing Rights', symbol: 'XDR' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'F CFA' },
  { code: 'XPF', name: 'CFP Franc', symbol: 'CFPF' },
  { code: 'XSU', name: 'Sucre', symbol: 'XSU' },
  { code: 'YER', name: 'Yemeni Rial', symbol: 'YER' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'ZAR' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZMW' },
  { code: 'ZWG', name: 'Zimbabwean Gold', symbol: 'ZWG' },
  { code: 'ZWL', name: 'Zimbabwean Dollar (2009–2024)', symbol: 'ZWL' },
];

/** Simbol mata uang; kode yang tak dikenal dipakai apa adanya. */
export const currencySymbol = (code) =>
  currencyList.find((c) => c.code === code)?.symbol || code || 'Rp';

/** Opsi siap pakai untuk StyledSelect: pencariannya ikut membaca baris kedua. */
export const currencyOptions = currencyList.map((c) => ({
  value: c.code,
  label: c.code,
  sub: c.name,
}));
